networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local

services:
  # PostgreSQL
  messaging-postgres:
    image: postgres:16.9-bullseye
    container_name: postgres
    restart: unless-stopped
    ports:
      - ":5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      PGPASSWORD: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    networks:
      - postgres-network
  #adminer
  adminer:
    image: adminer:5.2.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - postgres-network

