definitions:
  handlers.Credentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  title: API Authentification
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login and tokens JWT
      parameters:
      - description: User credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/handlers.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: JWT Tokens
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Login user
      tags:
      - auth
swagger: "2.0"
